bio/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('api', views.NewsViewsSet)

urlpatterns = [
    path('',views.index, name = 'index'),
    path('contact',views.contact, name = 'contact'),
    path('news', views.news, name = 'news'),
    path('category/<slug>', views.category_news, name='category'),
    path('news-details/<slug>', views.news_details, name='news_details'),
    path('page/<slug>', views.page, name='page'),
    path('news-api', views.news_api, name='news_api'),
    path('api/', include(router.urls))
]

hotel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('bio.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bio/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)

    def __str__(self):
        return self.name
    

class News(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=250)        
    slug = models.SlugField(max_length=250, unique=True)
    summary = RichTextField()
    description = RichTextField()
    is_published = models.BooleanField(default=True)
    photo = models.ImageField(upload_to='photos/%y/%m/%d/', blank=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Page(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to = 'page/%y/%m/%d/', blank=True)
    content = RichTextField()   

    def __str__(self):
        return self.title     

bio/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import JsonResponse

from .models import *
from django.http import HttpResponse
from django.core.mail import send_mail
from django.contrib import messages
from rest_framework import viewsets
from .serializers import NewsSerializer
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
import requests

class NewsViewsSet(viewsets.ModelViewSet):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = News.objects.all()
    serializer_class = NewsSerializer

    

# Create your views here.

def news_api(request):
    url="https://newsapi.org/v2/everything?q=tesla&from=2023-04-23&sortBy=publishedAt&apiKey=462359fb8553467a95bfef1e51acb8f1"
    response = requests.get(url)
    data = response.json()
    data = data['articles']
    send_data = {

        'newsData':data
    }
    return render(request, 'api.html', send_data)


def index(request):
    data={
        'categoryData': Category.objects.all(),
    }
    return render(request,'index.html', data)

def news(request):
    news_data=News.objects.all().values()
    news_data=list(news_data)
    return JsonResponse(news_data, safe=False)

    if request.method == 'POST':
        search=request.POST['search']
        find_data=News.objects.filter(title__icontains=search) | News.objects.filter(category__name__icontains=search)
        paginator = Paginator(find_data, 4) 
        page = request.GET.get('page')
        find_data = paginator.get_page(page)   

        data={
            'newsData':find_data,
            'title':'Search Result'
        }
        return render(request,'news.html',data)
    else:
        news_data=News.objects.all()
        paginator = Paginator(news_data, 3) 
        page = request.GET.get('page')
        news_data = paginator.get_page(page)    
    data={
        'newsData':news_data,
        'title':'All News'
    }
    return render(request,'news.html', data)

def contact(request):
    if request.method == 'POST':
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']     
        send_mail("Subject: " + subject, message, email, ['indramgr007@gmail.com'], fail_silently=False)   
        messages.success(request, 'Your message has been sent successfully')
        back = request.META.get('HTTP_REFERER')
        return redirect(back)
    else:
        return render(request,'contact.html')


def news_details(request, slug):
    newsData = News.objects.get(slug=slug)
    category = newsData.category.id
    related_news = News.objects.filter(category=category).exclude(id=newsData.id)
    data = {
        'newsData': News.objects.get(slug=slug),
        'related_news': related_news,
    }
    return render(request, 'news_details.html', data)

def global_data(request):
    data = {
            'categoryData':Category.objects.all(),
    }
    return data


def category_news(request,slug):
    data = {
        'catData':Category.objects.get(slug=slug),
    } 
    return render(request, 'category_news.html', data)


def page(request, slug):
    data={
        'pageContent': Page.objects.get(slug=slug),
    }
    return render(request,'page.html', data)
    

bio/templates/api.html
{% extends 'layouts/main.html' %}
{% block content %}

        
<div class="container mt-5 mb-5">
    <div class="row">                    
        <div class="col-md-12"> 
           <h1><a href="">News List</a></h1>
        </div>   
        <div class="row">
            {% for cNews in newsData %}
            <div class="col-md-4">
                <div class="card">
                    {% if cNews.urlToImage %}
                    <img src="{{ cNews.urlToImage }}" class="card-img-top" height="200" alt="...">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href=""{{ cNews.title }}</a>
                        </h5>
                        <p class="card-text">
                            {{ cNews.summary | safe }}
                        </p>
                        
                    </div> 
                </div>
            </div>
            {% endfor %}
        </div>  
     
        
    </div>
</div>

               



                  
                  
            
                    
               
        
    

{% endblock %}	


      
               

bio/templates/category_news.html
{% extends 'layouts/main.html' %}
{% block content %}

        
            <div class="container mt-5 mb-5">
                <div class="row">                    
                    <div class="col-md-12"> 
                       <h1><a href="">{{ catData.name }}</a></h1>
                    </div>   
                    <div class="row">
                        {% for cNews in catData.news_set.all %}
                        <div class="col-md-4">
                            <div class="card">
                                {% if cNews.photo %}
                                <img src="{{ cNews.photo.url }}" class="card-img-top" height="200" alt="...">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a href=""{{ cNews.title }}</a>
                                    </h5>
                                    <p class="card-text">
                                        {{ cNews.summary|safe }}
                                    </p>
                                    <a href="{% url 'news_details' cNews.slug %}" class="btn btn-primary">Go somewhere</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                </div>
            </div>    
                
            

{% endblock %}	


	

bio/templates/contact.html
{% extends 'layouts/main.html' %}
{% block content %}

<div class="contact">
    <div class="container">
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %} 
        </div>               

        <div class="col-md-5">
            <div class="contact-form">
                <form name="{% url 'contact' %}" method="post">        
                    {% csrf_token %}
                    <div class="form-group">                
                        <input type="email" name="email" required class="form-control" placeholder="Your Email"/>
                    </div>
                    <div class="form-group">
                        <input type="text" name="subject" required class="form-control" placeholder="Subject"/>
                    </div>              
                    <div class="form-group">
                        <textarea name="message" required class="form-control" rows="5" placeholder="Message"></textarea>
                    </div>                
                    <div class="form-group">                
                        <input type="submit" value="Send Message" class="btn btn-primary">                
                    </div>
                </form>
            </div>
        </div>
        <div id="fh5co-contact-section">
            <div class="row">
                <div class="col-md-4">
                    <div id="map" class="fh5co-map"></div>
                </div>
                <div class="col-md-6">
                    <div class="col-md-12">
                        <h3>Our Address</h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                        <ul class="contact-info">
                            <li><i class="ti-map"></i>198 West 21th Street, Suite 721 New York NY 10016</li>
                            <li><i class="ti-mobile"></i>+ 1235 2355 98</li>
                            <li><i class="ti-envelope"></i><a href="#">info@yoursite.com</a></li>
                            <li><i class="ti-home"></i><a href="#">www.yoursite.com</a></li>
                        </ul>
                    </div>
        </div>
        </div>
        {% endblock %}            

bio/templates/index.html
{% extends 'layouts/main.html' %}
{% block content %}

        
            <div class="container">
                <div class="row">
                    {% for category in categoryData %}
                        {% if category.news_set.all.count > 0 %}
                        <div class="col-md-12 mt-5">
                            <h1><a href="">{{ category.name }}</a></h1>
                            <div class="row">
                                {% for news in category.news_set.all %}
                                    <div class="col-md-4">
                                        <div class="card">
                                            {% if news.photo %}
                                            <img src="{{ news.photo.url }}" class="card-img-top" height="200" alt="...">
                                            {% endif %}
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    <a href=""{{ news.title }}</a>
                                                </h5>
                                                <p class="card-text">
                                                    {{ news.summary|safe }}
                                                </p>
                                                <a href="{% url 'news_details' news.slug %}" class="btn btn-primary">Go somewhere</a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}    
                            </div>
                        </div>    
                        {% endif %}    
                        
                    {% endfor %}       
                </div>    
            </div>
                
            

{% endblock %}	


	

bio/templates/layouts/footer.html
{% load static %}
<footer id="footer" class="fh5co-bg-color">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="copyright">
                    <p><small>&copy; 2016 Free HTML5 Template. <br> All Rights Reserved. <br>
                    Designed by <a href="http://freehtml5.co" target="_blank">FreeHTML5.co</a> <br> Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a></small></p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-3">
                        <h3>Company</h3>
                            {% for page in pageData %}
                            <a href="{% url 'page' page.slug %}">{{ page.title }}</a>
                            {% endfor %}
                    </div>
                    <div class="col-md-3">
                        <h3>Our Facilities</h3>
                        <ul class="link">
                            <li><a href="#">Resturant</a></li>
                            <li><a href="#">Bars</a></li>
                            <li><a href="#">Pick-up</a></li>
                            <li><a href="#">Swimming Pool</a></li>
                            <li><a href="#">Spa</a></li>
                            <li><a href="#">Gym</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <h3>Subscribe</h3>
                        <p>Sed cursus ut nibh in semper. Mauris varius et magna in fermentum. </p>
                        <form action="#" id="form-subscribe">
                            <div class="form-field">
                                <input type="email" placeholder="Email Address" id="email">
                                <input type="submit" id="submit" value="Send">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <ul class="social-icons">
                    <li>
                        <a href="#"><i class="icon-twitter-with-circle"></i></a>
                        <a href="#"><i class="icon-facebook-with-circle"></i></a>
                        <a href="#"><i class="icon-instagram-with-circle"></i></a>
                        <a href="#"><i class="icon-linkedin-with-circle"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

</div>
<!-- END fh5co-page -->

</div>
<!-- END fh5co-wrapper -->

<!-- Javascripts -->
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v16.0" nonce="LIQ1UTPx"></script>
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<!-- Dropdown Menu -->
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<!-- Counters -->
<script src="{% static 'js/jquery.countTo.js' %}"></script>
<!-- Stellar Parallax -->
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<!-- Owl Slider -->
<!-- // <script src="js/owl.carousel.min.js"></script> -->
<!-- Date Picker -->
<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
<!-- CS Select -->
<script src="{% static 'js/classie.js' %}"></script>
<script src="{% static 'js/selectFx.js' %}"></script>
<!-- Flexslider -->
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>

<script src="{% static 'js/custom.js' %}"></script>

</body>
</html>

bio/templates/layouts/header.html
<!DOCTYPE html>
{% load static %}

	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>
		{% if title %}
			{{ title }} : : Sunrise Boys Hostle : : Hotels
		{% else %}
			Sunrise Boys Hostle : : Hotels
		{% endif %}
	</title>
	<link rel="icon" href="{% static 'images/loc.png' %}"
	
 

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">
	<!-- <link href='https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700italic,900,700,900italic' rel='stylesheet' type='text/css'> -->

	<!-- Stylesheets -->
	<!-- Dropdown Menu -->
	<link rel="stylesheet" href="{% static 'css/superfish.css' %}">
	<!-- Owl Slider -->
	<!-- <link rel="stylesheet" href="css/owl.carousel.css"> -->
	<!-- <link rel="stylesheet" href="css/owl.theme.default.min.css"> -->
	<!-- Date Picker -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
	<!-- CS Select -->
	<link rel="stylesheet" href="{% static 'css/cs-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/cs-skin-border.css' %}">

	<!-- Themify Icons -->
	<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
	<!-- Flat Icon -->
	<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
	<!-- Icomoon -->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
	
	<!-- Style -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">	

</head>
<body>

bio/templates/layouts/main.html
{% include 'layouts/header.html' %}
{% include 'layouts/menu.html' %}

{% block content %}

{% endblock %}
 
{% include 'layouts/footer.html' %}

bio/templates/layouts/menu.html
	 <section class="ftco-section">
	 <div class="container">
	 <div class="row justify-content-center">
	 <div class="col-md-6 text-center mb-5">
	
	 </div>
	 </div>
	 </div>
	 <div class="container">
	 <div class="row justify-content-between">
	 <div class="col">
	 <a class="navbar-brand" href="index.html"></a>
	 </div>
	 {% comment %} <div class="col d-flex justify-content-end"> {% endcomment %}
	 <div class="col-md-2">
		<ul class="social-icons">
			<li>
				<a href="#"><i class="icon-twitter-with-circle"></i></a>
				<a href="#"><i class="icon-facebook-with-circle"></i></a>
				<a href="#"><i class="icon-instagram-with-circle"></i></a>
				<a href="#"><i class="icon-linkedin-with-circle"></i></a>
			</li>
		</ul>
	 </div>
	 </div>
	 </div>
	 </div>
	 </div>
	 <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
		<div class="container">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="fa fa-bars"></span> Menu
		</button>
		{% comment %} <form action="#" class="searchform order-lg-last">
		<div class="form-group d-flex">
		<input type="text" class="form-control pl-3" placeholder="Search">
		<button type="submit" placeholder="" class="form-control search"><span class="fa fa-search"></span></button>
		</div>
		</form>  {% endcomment %}
		
	 
	 

	 <div class="collapse navbar-collapse" id="ftco-nav">
	 <ul class="navbar-nav mr-auto">
	 <li class="nav-item active"><a href="/" class="nav-link">Home</a></li>
	 <li class="nav-item dropdown">
	 <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Category</a>
	 <div class="dropdown-menu" aria-labelledby="dropdown04">
		{% for category in categoryData %}	
		<a href="{% url 'category' category.slug %}" class="dropdown-item">{{ category.name }}</a>
		{% endfor %}
	 </div>
	 </li>
	 
	 <li class="nav-item"><a href="{% url 'news_api' %}" class="nav-link">News API</a></li>
	 <li class="nav-item"><a href="{% url 'news' %}" class="nav-link">News</a></li>
	 <li class="nav-item"><a href="{% url 'contact' %}" class="nav-link">Contact</a></li>
	 </ul>
	 </div>
	 </div>
	 <div class="col-lg-3 col-md-4">
		<form action="{% url 'news' %}" method="post">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-10">
					<input type="text" class="form-control" required name="search">
					
				</div>
				<div class="col-md-2" style="padding-left:0;">
					<button type="submit" class="btn btn-primary">Search</i></button>
					</button>
				</div>
			 </div>
		</form>
	 </div>

	 </nav>
	 
	 </section>
	 
 	 
	 <script src="js/jquery.min.js"></script>
	 <script src="js/popper.js"></script>
	 <script src="js/bootstrap.min.js"></script>
	 <script src="js/main.js"></script>
	 <script defer src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816" integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw==" data-cf-beacon='{"rayId":"7c9b09f6ba399e7d","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2023.4.0","si":100}' crossorigin="anonymous"></script>
	 </body>
	 </html> 
	 

bio/templates/news.html
{% extends 'layouts/main.html' %}
{% block content %}

        
<div class="container mt-5 mb-5">
    <div class="row">                    
        <div class="col-md-12"> 
           <h1><a href="">News List</a></h1>
        </div>   
        <div class="row">
            {% for cNews in newsData %}
            <div class="col-md-4">
                <div class="card">
                    {% if cNews.photo %}
                    <img src="{{ cNews.photo.url }}" class="card-img-top" height="200" alt="...">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href=""{{ cNews.title }}</a>
                        </h5>
                        <p class="card-text">
                            {{ cNews.summary | safe }}
                        </p>
                        <a href="{% url 'news_details' cNews.slug %}" class="btn btn-primary">Go somewhere</a>
                    </div> 
                </div>
            </div>
            {% endfor %}
        </div>  
        <div class="row mt-5 mb-5">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if newsData.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ newsData.previous_page_number }}">Previous</a>
                        </li>
                    {% endif %}
                    {% for i in newsData.paginator.page_range %}
                        {% if newsData.number == i %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% else %}    
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endif %}         
                    {% endfor %} 
                    {% if newsData.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ newsData.next_page_number }}">Next</a>
                        </li>
                    {% endif %} 
                </ul>
            </nav>
        </div> 
        
    </div>
</div>

               



                  
                  
            
                    
               
        
    

{% endblock %}	


      
               

bio/templates/news_details.html
{% extends 'layouts/main.html' %}
{% block content %}

        
            <div class="container mt-5 mb-5">
                <div class="row">                    
                    <div class="col-md-8"> 
                        <h1><a href="">{{ newsData.title }}</a></h1>                     
                        {% if newsData.photo %}
                            <img src="{{ newsData.photo.url }}" class="img-fluid" height="200" alt="">
                        {% endif %}
                        <p>{{ newsData.description | safe }}</p>
                    </div>   
                    <div class="col-md-4">
                    <h1>Related News</h1>     
                        <ul>
                            {% for rNews in related_news %}
                            <li><a href="{% url 'news_details' rNews.slug %}">{{ rNews.title }}</a></li>
                            {% endfor %}
                            
                    </div>    
                </div>
            </div>  
        <div class="row">  
            <div id="fb-root"></div>
            <div class="fb-comments" data-href="http://127.0.0.1:8000/news/{{ newsData.slug }}" data-width="" data-numposts="">

            </div>"    
        </div>          
            
{% endblock %}	


	

bio/templates/page.html
{% extends 'layouts/main.html' %}
{% block content %}  

<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-8">
            <h1>{{ pageContent.title }}<?h1>
            <p>{{ pageContent.content|safe }}</p>  
        </div>
    </div>
</div>
        
                  
{% endblock %}	


      
               